Add QuickJS as a Javascript engine option
https://bellard.org/quickjs
https://fuchsia.googlesource.com/third_party/quickjs/

Some benefits over SM:

 * Small. We're using 6 or so C files vs 700+ SM91 C++ files.

 * Built with Apache CouchDB as opposed having to maintain a separate SM
   package, like for RHEL9, for instance, where they dropped support for SM
   already. (see https://github.com/apache/couchdb/issues/4154).

 * Embedding friendly. Designed from ground-up for embedding. SM has been
   updating the C++ API such that we have to keep copy-pasting new versions of
   our C++ code every year or so. (see
   https://github.com/apache/couchdb/pull/4305).

 * Easy to modify to accept Spidermonkey 1.8.5 top level functions for
   map/reduce code so we don't have have to parse the JS, AST transform it, and
   then re-compile it.

 * Configurable runtime feature set - can disable workers, promises and other
   API and features which may not work well in a backend JS environment. Some
   users may want more, some may want to disable even Date(time) features to
   hedge again Spectre-style attacks (spectreattack.com).

 * Allows granular time (reduction) tracking if we wanted to provide a runtime
   allowance for each function.

 * Better sandboxing. Creating a whole JSRuntime takes only 300 microseconds, so
   we can afford to do that on reset. JSRuntimes cannot share JS data or object
   between them.

 * Seems to be faster in preliminary benchmarking with small
   concurrent VDU and view builds:
     https://gist.github.com/nickva/ed239651114794ebb138b1f16c5f6758
   Results seem promising:
     - 4x faster than SM 1.8.5
     - 5x faster than SM 91
     - 6x reduced memory usage per couchjs process (5MB vs 30MB)

 * Allows compiling JS bytecode ahead of time a C array of bytes.

QuickJS can be built alongside Spidermonkey and toggled on/off at runtime:

```
./configure --dev --js-engine=quickjs
```

This makes it the default engine. But Spidermonkey can still be set in the
config option.

```
[couchdb]
js_engine = spidermonkey | quickjs
```

Only tested on MacOS and Linux. All `make check` tests pass there.

Issue: https://github.com/apache/couchdb/issues/4448

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -36,6 +36,7 @@ run_erlang() {
 }
 
 COUCHDB_USER="$(whoami 2>/dev/null || echo couchdb)"
+JS_ENGINE=${JS_ENGINE:-"spidermonkey"}
 SM_VSN=${SM_VSN:-"91"}
 ARCH="$(uname -m)"
 ERLANG_VER="$(run_erlang 'io:put_chars(erlang:system_info(otp_release)).')"
@@ -65,6 +66,7 @@ Options:
   --rebar=PATH                use rebar by specified path (version >=2.6.0 && <3.0 required)
   --rebar3=PATH               use rebar3 by specified path
   --erlfmt=PATH               use erlfmt by specified path
+  --js-engine=ENGINE          default js engine: spidermonkey or quickjs
 EOF
 }
 
@@ -200,6 +202,24 @@ parse_opts() {
                 printf 'ERROR: "--spidermonkey-version" requires a non-empty argument.\n' >&2
                 exit 1
                 ;;
+            --js-engine)
+                if [ -n "$2" ]; then
+                    eval JS_ENGINE=$2
+                    shift 2
+                    continue
+                else
+                    printf 'ERROR: "--js-engine" requires a non-empty argument.\n' >&2
+                    exit 1
+                fi
+                ;;
+            --js-engine=?*)
+                eval JS_ENGINE=${1#*=}
+                ;;
+            --js-engine=)
+                printf 'ERROR: "--js-engine" requires a non-empty argument.\n' >&2
+                exit 1
+                ;;
+
 
             --) # End of options
                 shift
@@ -223,7 +243,7 @@ if [ "${ARCH}" = "aarch64" ] && [ "${SM_VSN}" = "60" ]; then
   exit 1
 fi
 
-if [ "${ERLANG_OS}" = "unix" ]; then
+if [ "${JS_ENGINE}" = "spidermonkey" ] && [ "${ERLANG_OS}" = "unix" ]; then
     case "${SM_VSN}" in
         1.8.5)
             SM_HEADERS="js"
@@ -265,6 +285,7 @@ cat > rel/couchdb.config << EOF
 {log_file, "$LOG_FILE"}.
 {fauxton_root, "./share/www"}.
 {user, "$COUCHDB_USER"}.
+{js_engine, "$JS_ENGINE"}.
 {spidermonkey_version, "$SM_VSN"}.
 {node_name, "-name couchdb@127.0.0.1"}.
 {cluster_port, 5984}.
@@ -294,12 +315,14 @@ with_docs = $WITH_DOCS
 with_nouveau = $WITH_NOUVEAU
 
 user = $COUCHDB_USER
+js_engine = $JS_ENGINE
 spidermonkey_version = $SM_VSN
 EOF
 
 cat > $rootdir/config.erl << EOF
 {with_proper, $WITH_PROPER}.
 {erlang_md5, $ERLANG_MD5}.
+{js_engine, "$JS_ENGINE"}.
 {spidermonkey_version, "$SM_VSN"}.
 EOF
 
